restructured repo, removed web3, added ethers
zgendao/agora.space pull request #27
Opened 2021-05-01 19:37 UTC by richardanyalai

Closes #26

2021-05-01 20:16 UTC, TomiOhl requested changes

2021-05-01 20:16 UTC, TomiOhl commented on telegram/package.json
> +    "@truffle/hdwallet-provider": "^1.2.3",
OpenZeppelin contracts and hdwallet provider are dependencies of the contracts, so we will need another package.json  elsewhere with those I guess (?)

2021-05-03 21:37 UTC, TomiOhl approved these changes
gtg now

2021-05-05 10:36 UTC, dovalid approved these changes

2021-05-05 10:39 UTC, merged